@include('miembros._form.personal')
<br>
@include('miembros._form.contacto')
<br>
@include('miembros._form.vivienda')
<br>
@include('miembros._form.actividad')
<br>
@include('miembros._form.registro')
<br>
@include('miembros._form.fotografia')
@csrf
